name: Pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
        # with:
        # options to pass to pre-commit run
        # extra_args: # optional, default is --all-files 
